### ISSUE TITLE
Visual overview of the spec

### ISSUE THREAD

**Issue by bjdmeest** [kg-construct/collection-containers-spec#25]
I'm wondering whether a visual overview of this extension would make sense to include, to get the gist very quickly,

something like below

```mermaid
classDiagram
  direction BT

  class GatherMap {
    @type TermMap

    TermMap[] rml:gather 1
    [rml:Append rml:CartesianProduct] rml:strategy 0..1 rml:Append
    [rdf:Seq, rdf:Bag, rdf:Alt, rdf:List] rml:gatherAs 1
    xsd:boolean rml:allowEmptyListAndContainer 0..1 "false"
    }

```

**Comment by pmaria** [comment]
We also have the diagrams.net overview diagrams which would be good to update as well.

**Comment by dachafra** [comment]
Agree! I think @anaigmo could help a bit on this, and we can follow a similar approach as we did for `RML-star` https://kg-construct.github.io/rml-star-spec/, so all the diagrams are consistent between specs

**Comment by anaigmo** [comment]
Sure! I'll start with collections+containers, and then update the rest

**Comment by dachafra** [comment]
The new diagram is available in diagrams.net file, so @frmichel @chrdebru you can add it to the spec.

**Comment by chrdebru** [comment]
Thanks! It took me a while, but I found the image in `KGC CG-W3C (all)/Brainstormings/`. Thanks, @anaigmo.

**Comment by anaigmo** [comment]
Hi all,

According to recent discussions, I remade the diagram for containers and collections, so that it only includes the class in which it connects to the core, but not the whole core as it is now. The original diagram is still in the same location @chrdebru mentions in the last comment.


![RML-collections-containers](https://user-images.githubusercontent.com/36294992/208887643-8c02f01a-6bba-4141-aa5e-ddf5c2432eca.png)

**Comment by frmichel** [comment]
Thx for this @anaigmo, that looks good to me.

**Comment by pmaria** [comment]
@anaigmo Great work!

I have one remark and that is regarding `rml:strategy`. In #23 we decided to leave the domain of `rml:Strategy` open, so that it can be used more genrally. So that begs the question: What is this image depicting? Is it the ontology, or is it the shapes for this spec, or both?

I guess this is a general question :)

**Comment by frmichel** [comment]
I would understand that the legend answers your question: rml:strategy is an object prop, therefore it relates instances, and rml:Append and rml:CartesianProduct are the objects of this property. This leaves room for creating new instances of rml:Strategy.
Maybe just a typo concern, should we name the instances rml:append and rml:cartesianProduct to stick to the rule that classe names start with a capital letter?

**Comment by anaigmo** [comment]
Thanks @pmaria :) I decided to represent only the ontology and leave all restrictions, apart from domain/range, out of the diagrams, partially because some would complicate the images, but we can change and try to represent everything. I loosely follow the diagram notation of [Chowlk](https://chowlk.linkeddata.es/notation.html), so I can open the domain of `rml:strategy` as you suggest. 

Regarding @frmichel 's comment, agree with the first part; and I'll rename the instances to stick with the rule. 

Thanks both for the feedback!

**Comment by frmichel** [comment]
> I'll rename the instances to stick with the rule.

Ok I will do that too on the spec itself.

Thx,
    Franck.

Le 21/12/2022 à 14:43, Ana Iglesias a écrit :
