### ISSUE TITLE
Building a collection/container through multiple iterations with self-join

### ISSUE THREAD

**Issue by bjdmeest** [kg-construct/collection-containers-spec#26]
For my clarification, could you provide an example if I want to convert

```json
{
  "values": [
    {
      "parentId": "a"
      "values": ["1", "2", "3"]
    },
    {
      "parentId": "a"
      "values": ["4", "5", "6"]
    },
    {
      "parentId": "b"
      "values": ["7", "8", "9"]
    }
  ]
}
```

into

```turtle
<list/a> rdf:_1 ("1" "2" "3") ; rdf:_2 ("4" "5" "6") .
<list/b> rdf:_1 ("7" "8" "9") .
```

**Comment by chrdebru** [comment]
Unless there was a reason for `values` in de document, we have renamed the first one into `top` so that the example becomes easier to trace. The problem in this (interesting) example is that this requires a join (on values) ; in other words, **join across iterations** instead of **aggregating different aggregations from the same iteration**. So they cannot be nested.  We must do this example with a "normal" parent triples map.

```
{
  "top": [
    {
      "parentId": "a"
      "values": ["1", "2", "3"]
    },
    {
      "parentId": "a"
      "values": ["4", "5", "6"]
    },
    {
      "parentId": "b"
      "values": ["7", "8", "9"]
    }
  ]
}```

Here's the proposed mapping solution:
```<#TMTOP> a rr:TriplesMap;
  rml:logicalSource [
    rml:source "data.json" ;
    rml:referenceFormulation ql:JSONPath ;
    rml:iterator "$.top.*" ;
  ] ;

  rr:subjectMap [
      rr:template "bag/{parendId}" ;
      rml:gather ( 
        [ 
            rr:parentTriplesMap <#TMVALUES>;
            rr:joinCondition [ rr:child "parendId" ; rr:parent "parendId" ; ] ;
        ]) ;
      rml:gatherAs rdf:Bag ;
  ] ;
.

<#TMVALUES> a rr:TriplesMap;
  rml:logicalSource [
        rml:source "data.json" ;
        rml:referenceFormulation ql:JSONPath ;
        rml:iterator "$.top.*" ;
  ] ;

  rr:subjectMap [
        rr:termType rr:BlankNode ;
        rml:gather ( [ rml:reference "values.*" ; ] ) ;
        rml:gatherAs rdf:List ;
  ] ;
.```

IMHO: nested gather maps would have been possible if we could change the iteration inside a term map (go one up and fetch). Maybe fields can provide another interesting solution as well.

**Comment by bjdmeest** [comment]
The solution seems very clean imo so that's great, I didn't realize you could do a join within a gather within a subjectmap where the parentTriplesMap generates a list as its subject (feels like an edge case on top of an edge case on top of an edge case).

Indeed changing the iteration within a term map could potentially create alternative ways of describing this, but I think I'm leaning towards _not_ supporting changing the iteration model within a term map, as that complicates things a whole damn lot :)
